spring:
  datasource:
    tracker:
      jdbc-url: jdbc:h2:file:./db/tracker
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console

node:
  mode: ganache
  ropsten:
    url: https://ropsten.infura.io/v3/
  ganache:
    url: http://127.0.0.1
    port: 8545

tracker:
  address: dE855e7bBd97b1aE3aBa872e62Cb4C555A709Fe9

tx:
  queue-size: 10
  thread-pool: 20

server:
  port: 8081
