spring:
  datasource:
    tracker:
      jdbc-url: jdbc:h2:file:./db/tracker
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console

node:
  mode: infura
  parity:
    url: http://45.32.21.50
    port: 8545/
  infura:
    url: https://ropsten.infura.io/v3
    key: 4feb1e5949df453fa6326d4328fe5b80
  ganache:
    url: http://127.0.0.1
    port: 8545

etherscan:
  api:
    key: XKSJ7APNM5F9PR5R4P5W84S6IXW95BW7MK

tracker:
  address: dE855e7bBd97b1aE3aBa872e62Cb4C555A709Fe9

tx:
  queue-size: 10000
  thread-pool: 24

server:
  port: 8080
